### ISSUE TITLE
Attribute missing from plot object

### ISSUE THREAD

**Issue by egravenh** [pyansys/pyfluent-visualization#113]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

The following error is printed and the plot fails to display:

AttributeError: 'FigureCanvasQTAgg' object has no attribute 'set_window_title' Did you mean: 'setWindowTitle'?

### 📝 Steps to reproduce

To reproduce:
1) Packages

pip install --pre ansys-fluent-core
pip install --pre ansys-fluent-visualization

2) Environment variables

               PYFLUENT_FLUENT_ROOT = %AWP_ROOT222%\fluent
               PYFLUENT_SHOW_SERVER_GUI = 1

3) Open a python interpreter and enter the following:

import ansys.fluent.core as pyfluent
from ansys.fluent.core import examples

from ansys.fluent.visualization import set_config
from ansys.fluent.visualization.matplotlib import Plots

set_config(blocking=True, set_view_on_display="isometric")

import_case = examples.download_file(
    filename="exhaust_system.cas.h5", directory="pyfluent/exhaust_system"
)

import_data = examples.download_file(
    filename="exhaust_system.dat.h5", directory="pyfluent/exhaust_system"
)

solver_session = pyfluent.launch_fluent(
    precision="double", processor_count=2, start_transcript=False, mode="solver"
)

solver_session.tui.file.read_case(case_file_name=import_case)
solver_session.tui.file.read_data(case_file_name=import_data)

plots_session_1 = Plots(solver_session)
xy_plot = plots_session_1.XYPlots["xy-plot"]
xy_plot.surfaces_list = ["outlet"]
xy_plot.y_axis_function = "temperature"
xy_plot.plot("window-1")

### 💻 Which operating system are you using?

Windows

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
pip install --pre ansys-fluent-core
pip install --pre ansys-fluent-visualization
```

**Comment by mkundu1** [comment]
The issue is with `matplotlib-3.6.0rc2`. The latest release version `matplotlib-3.5.3` works fine. I'm not sure why it is pulling an RC version.

**Comment by mkundu1** [comment]
It seems the `--pre` flag pulls the pre-release versions of dependencies too. This won't be an issue for users. Please execute `pip install matplotlib==3.5.3` to downgrade matplotlib to the latest release version where the issue is not reproducible.
