### ISSUE TITLE
Local development instructions not working

### ISSUE THREAD

**Issue by dnwillia-work** [pyansys/pyfluent-visualization#122]
![image](https://user-images.githubusercontent.com/18702052/188653885-17266c89-5335-48ae-b536-4c73167a76f9.png)

`pip install -e .` is not working with the `pyproject.toml`.

**Comment by seanpearsonuk** [comment]
Hi @dnwillia-work, did you mean to create the issue in pyfluent-parametric?

**Comment by mkundu1** [comment]
@dnwillia-work Is this due to pip version? `pip install -e .` works for me for both parametric and visualization. My pip version 22.2.2.

**Comment by dnwillia-work** [comment]
Ah, well... that could be.  Let me check.

**Comment by dnwillia-work** [comment]
As @mkundu1 points out, this is due to requiring a newer pip version than what I had installed locally.  Upgrading to 22.2.2 makes it work.

Not sure what to do about it, if anything.  The error you get is a bit opaque:
```
(venvtest) D:\ANSYSDev\NoBackup\pyansys\pyfluent-visualization>pip install -e .
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: D:\ANSYSDev\NoBackup\pyansys\pyfluent-visualization
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
WARNING: You are using pip version 21.1.1; however, version 22.2.2 is available.
You should consider upgrading via the 'd:\ansysdev\nobackup\pyansys\pyfluent-visualization\venvtest\scripts\python.exe -m pip install --upgrade pip' command.
```

**Comment by mkundu1** [comment]
I think the previous line in the README `pip install pip -U` should update pip for users.

**Comment by dnwillia-work** [comment]
Well, I guess you can't protect me from not reading carefully.  :-).
